version: "2"

services:
  api:
    build: ./app
    image: nextbus-ng-api
    restart: always
    volumes:
     - ./app:/app:ro
    expose:
     - "8080"
    depends_on:
     - redis1
     - redis2
    dns: 10.0.2.2
    environment:
     - VIRTUAL_HOST=nextbus-web
     - VIRTUAL_PORT=8080

  redis1:
    image: redis:alpine
    expose:
     - "6379"

  redis2:
    image: redis:alpine
    links:
     - redis1
    expose:
     - "6379"

  lb:
    build: ./conf/nginx
    image: nextbus-ng-lb
    restart: always
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
     - api
    depends_on:
     - api
    ports:
     - "80:80"
    expose:
     - "80"
