version: "2"

services:
  nextbus-web-1:
    build: .
    restart: always
    volumes:
     - ./app:/app:ro
    expose:
     - "8080"
  
  nextbus-web-2:
    build: .
    restart: always
    volumes:
     - ./app:/app:ro
    expose:
     - "8080"
  
  nextbus-web-3:
    build: .
    restart: always
    volumes:
     - ./app:/app:ro
    expose:
     - "8080"
  
  nextbus-web-4:
    build: .
    restart: always
    volumes:
     - ./app:/app:ro
    expose:
     - "8080"
  
  redis-1:
    image: redis:alpine
    expose:
     - "6379"
  
  redis-2:
    image: redis:alpine
    links:
     - redis-1
    expose:
     - "6379"
  
  lb-1:
    image: nginx:alpine
    restart: always
    volumes:
        - ./conf/nginx/nextbus.conf:/etc/nginx/nginx.conf:ro
    links:
     - nextbus-web-1
     - nextbus-web-2
     - nextbus-web-3
     - nextbus-web-4
    ports:
     - "80:80"
    expose:
     - "80"
  
  lb-2:
    image: nginx:alpine
    restart: always
    volumes:
        - ./conf/nginx/nextbus.conf:/etc/nginx/nginx.conf:ro
    links:
     - nextbus-web-1
     - nextbus-web-2
     - nextbus-web-3
     - nextbus-web-4
    ports:
     - "81:80"
    expose:
     - "80"
