version: "2"

services:
  nextbus-web:
    build: ./app
    restart: always
    volumes:
     - ./app:/app:ro
    expose:
     - "8080"
    depends_on:
     - redis-1
    environment:
     - VIRTUAL_HOST=nextbus-web
     - VIRTUAL_PORT=8080
  
  redis-1:
    image: redis:alpine
    expose:
     - "6379"
  
  redis-2:
    image: redis:alpine
    links:
     - redis-1
    expose:
     - "6379"
  
  lb-1:
    build: ./conf/nginx
    restart: always
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
     - nextbus-web
    depends_on:
     - nextbus-web
    ports:
     - "80:80"
    expose:
     - "80"
